# Generated by Django 5.1.6 on 2025-09-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_aicost_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicost',
            name='cost',
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
    ]
