# Generated by Django 5.1.6 on 2025-10-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='post_type',
            field=models.CharField(choices=[('MEDIA', 'MEDIA')], max_length=256),
        ),
    ]
